Repository boardGame12/vikings-chess, pull requests merged in 2024-01, with the labels that each got.

#17 Homeandregistration
  Images/scroll.png
  svgFiles/Home.svg
  svgFiles/Login.svg
  svgFiles/Registration.svg
  svgFiles/Reset Password.svg
  svgFiles/Scroll.svg
Labels: documentation

#35 Call sprites
  Scss/style.css
  Scss/style.css.map
  Scss/style.scss
  Sprites/rbsprites.png
  play.css
  play.html
  play.js
Labels: enhancement

#36 made some changes to the responsiveness
  Scss/style.css
  Scss/style.css.map
  Scss/style.scss
Labels: css added

#38 added rules to enforce legal moves and turns
  about.html
  creator.html
  index.html
  play.html
  play.js
  register.html
  rules.html
Labels: added JavaScript

#39 rules page made and index links updated
  Scss/style.css
  Scss/style.css.map
  Scss/style.scss
  index.html
  rules.html
Labels: css added

#40 added capture logic
  .gitignore
  Sprites/red_blue_sprites.png
  play.js
  svgFiles/sprites.png
Labels: enhancement

#42 about page is finished with link to video
  about.html
Labels: css added

#43 added movement rules and bug fixes
  play.js
Labels: bug, added JavaScript

#44 added 3 side king capture when on border
  play.js
Labels: added JavaScript

#45 Choose player page
  Scss/style.css
  Scss/style.css.map
  Scss/style.scss
  playerChoice.html
Labels: css added

#46 added computer opponent
  play.js
Labels: added JavaScript

#47 added run loop
  play.js
Labels: added JavaScript

#48 Register
  Scss/style.css
  Scss/style.css.map
  Scss/style.scss
  index.html
  register.html
Labels: css added
